advent:
    url: https://adventproperties.appfolio.com/listings/?1463542934435
    base: https://adventproperties.appfolio.com
    parser: advent
    javascript: True
slpm:
    url: https://slpm.appfolio.com/listings?1408551123197
    base: https://slpm.appfolio.com
    parser: advent
    javascript: True
crpm:
    url: https://communityrealtypm.appfolio.com/listings/?1463635612438
    base: https://communityrealtypm.appfolio.com
    parser: advent
    javascript: True
bay_property_group:
    url: https://baypropertygroup.appfolio.com/listings/?1463636254783
    base: https://baypropertygroup.appfolio.com
    parser: advent
    javascript: True
discovery:
    url: https://discovery.appfolio.com/listings/?1463637442457
    base: https://discovery.appfolio.com
    parser: advent
    javascript: True
cwp:
    url: https://cwp.appfolio.com/listings/?1463673996972
    base: https://cwp.appfolio.com
    parser: advent
    javascript: True
openworld:
    url: http://openworld.appfolio.com/listings?1463675923117
    base: http://openworld.appfolio.com
    parser: advent
    javascript: True
msb:
    url: https://msbpropertymanagement.appfolio.com/listings/?1463676684673
    base: https://msbpropertymanagement.appfolio.com
    parser: advent
    javascript: True
sg:
    url: https://sgrealestate.appfolio.com/listings/?1464738450587
    base: https://sgrealestate.appfolio.com
    parser: advent
    javascript: True